CREATE SCHEMA "public";

CREATE SEQUENCE "public".customer_id_seq START WITH 1;

CREATE SEQUENCE "public".groups_id_seq START WITH 1;

CREATE TABLE "public".groups ( 
	id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	title                text  NOT NULL ,
	description          text   ,
	CONSTRAINT pk_groups_id PRIMARY KEY ( id )
 );

COMMENT ON TABLE "public".groups IS 'A table of groups that contacts belong to.';

COMMENT ON COLUMN "public".groups.id IS 'The id of the group.';

COMMENT ON COLUMN "public".groups.title IS 'The title of the group.';

COMMENT ON COLUMN "public".groups.description IS 'The description of the group.';

CREATE TABLE "public".contacts ( 
	id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name                 text  NOT NULL ,
	description          text  NOT NULL ,
	birthdate            date  NOT NULL ,
	"group"              integer  NOT NULL ,
	created_timestamp    timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL ,
	updated_timestamp    timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL ,
	favorite_flag        text   ,
	CONSTRAINT pk_customer_id PRIMARY KEY ( id )
 );

CREATE INDEX idx_contacts_group ON "public".contacts ( "group" );

COMMENT ON TABLE "public".contacts IS 'A table containing customer entities.';

COMMENT ON COLUMN "public".contacts.id IS 'The id of the customer.';

COMMENT ON COLUMN "public".contacts."group" IS 'The group that the contact belons to.';

COMMENT ON COLUMN "public".contacts.created_timestamp IS 'The time that the customer was added.';

COMMENT ON COLUMN "public".contacts.updated_timestamp IS 'The time that the customer entity was updated.';

COMMENT ON COLUMN "public".contacts.favorite_flag IS 'The flag that is the favorite of the contact.';

ALTER TABLE "public".contacts ADD CONSTRAINT fk_contacts_groups FOREIGN KEY ( "group" ) REFERENCES "public".groups( id ) ON DELETE CASCADE ON UPDATE CASCADE;

COMMENT ON CONSTRAINT fk_contacts_groups ON "public".contacts IS 'The foreign key to the groups table.';
